apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "node-server.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }} 